# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/masiroyuki"

[social.params]
icon = "brand-github"

[[social]]
identifier = "X"
name = "X"
url = "https://twitter.com/koremazikbtit"

[social.params]
icon = "brand-twitter"
